excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sichuanzaier.github.io
title: tech tips for you
email: z798992590@gmail.com
author: owen
description: My awesome new site
paginate: 3
google_analytics: 